console.log(Boolean(null));
console.log(Boolean(undefined));
console.log(Boolean(0));
console.log(Boolean(+0));
console.log(Boolean(-0));
console.log(Boolean(NaN));
console.log(Boolean(""));
console.log(Boolean("Joey Rules"));
console.log(Boolean(100));
console.log(Boolean({}));
console.log(Boolean([]));