console.log(!10);
console.log(!0);
console.log(!(+0));
console.log(!(-0));
console.log(!NaN);
console.log(!undefined);
console.log(!null);
console.log(!true);
console.log(!false);
console.log(!"");
console.log(!" ");
console.log(!"Hi");
console.log(!{});
console.log(!{x: 10});