console.log("" + "Hi");
console.log("" + 5);
console.log("" + (+0));
console.log("" + (-0));
console.log("" + (+12));
console.log("" + (-12));
console.log("" + NaN);
console.log("" + true);
console.log("" + false);
console.log("" + undefined);
console.log("" + null);
console.log("" + {x: 10});
console.log("" + {x: 10, toString() {return 10;}});